model:
  model_path: model.testcnn #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: CNN
  param: 
    in_features : (2,70,161,161)
    out_features: (70,161,161)

data: 
  data_path : ./dataset #the folder of 3 npy file
  npy_name: ('data1.npy', 'data2.npy', 'data3.npy') # order: target_npy, input1.npy, input2.npy, if None, write (a.npy, None, None)
  npy_len: (7304 , -1, -1) #3-tuple, set -1 if the npy not exist 
  # 14612 for 2007-2016
  preload_to_memory: False
  argument: False
  train_range: [2007,2008]
  val_range: [2008,2009]

train: 
  finetune: 
    fintune: True
    steps: 2
    only_optim_last: False
    checkpoint_path: ./checkpoints/test.pth
    
  optimizer:
    name: Adam
    learning_rate: 0.00001
    weight_decay: 1e-5
  n_epochs: 1  
  ckpt_dir: checkpoint
  device: cuda:1
  autoregressive: True

  dataloader:
    num_workers: 8
    batch_size_train: 64
    batch_size_val: 64

logger: #default wandb
#   project: weather-forecast
#   name: swin-run-AR

seed: 114514

