model:
  model_path: torch_harmonics.examples.sfno #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: SphericalFourierNeuralOperatorNet
  param: 
    spectral_transform: sht 
    operator_type: driscoll-healy
    img_size: [32, 64]
    grid: "equiangular"
    num_layers: 8
    scale_factor: 1
    embed_dim: 768
    big_skip: True
    pos_embed: "lat"
    use_mlp: False
    normalization_layer: none
    in_chans: 68
    out_chans: 68

data: 
  data_path : /dev/shm/store/checkpoint/original_dataset
  npy_name: /dev/shm/store/original_dataset/dataset.npy
  shape: [58436, 68, 32, 64]
  preload_to_memory: False
  augment: False
  train_range: [0,56000]
  val_range: [56000,58436]

train: 
  optimizer:
    name: Adam
    learning_rate: 1
    weight_decay: 1e-5
    scheduler: 
      name: NoamLR
      hidden_dim: 192
      warmup_steps: 1000
  n_epochs: 200  
  ckpt_dir: /home/gaoziyi/weather/deepspeed_checkpoint
  device: cuda:0
  autoregressive: True
  validate_step : 500
  # time_regularization: True
  time_regularization: False
  time_regularization_weight: 1

  batch_size: 64

  restore_session:
    yes: False
    load_dir: checkpoint
    ckpt_id: 200

  dataloader:
    num_workers: 32
    batch_size: 64
    prefetch_factor: 32

  deepspeed_config: ./cfgs/deepspeed.json

logger: #default wandb
    project: weather-forecast-deepspeed
    name: SFNO-layernorm-downsample1

seed: 114514

hydra:
  run:
    dir: null

    

# from torch_harmonics.examples.sfno import SphericalFourierNeuralOperatorNet as SFNO