model:
  model_path: model.swin_unet #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: SwinTransformerSys
  param: 
    in_seq_length: 2
    out_seq_length: 20
    input_dim: 70
    output_dim: 5
    lat_dim: 161
    lon_dim: 161 # now must be same as lat_dim    # above are input and output parameters
    patch_size: 4
    hidden_dim: 192
    window_size: 5

data: 
  data_path : ../dataset
  augment: False
  batch_size_train: 64
  batch_size_val: 64
train: 
  optimizer:
    name: Adam
    learning_rate: 0.00001
    weight_decay: 1e-5
  n_epochs: 100  
  ckpt_dir: checkpoint
  device: cuda:1

logger: #default wandb
  project: weather-forecast
  name: Swin_UNet_run

