model:
  model_path: model.swin_unet #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: SwinTransformerSys
  param: 
    param: 
    in_seq_length: 2
    out_seq_length: 1
    input_dim: 70
    output_dim: 70
    lat_dim: 161
    lon_dim: 161 # now must be same as lat_dim    # above are input and output parameters
    patch_size: 2
    hidden_dim: 384
    window_size: 10


data: 
  data_path : /local_ssd/gaoziyi/dataset
  npy_name: /local_ssd/gaoziyi/dataset/dataset.npy
  preload_to_memory: False
  augment: False
  train_range: [2007,2016]
  val_range: [2016,2017]

train: 
  optimizer:
    name: Adam
    learning_rate: 1
    weight_decay: 1e-5
    scheduler: 
      name: NoamLR
      hidden_dim: 192
      warmup_steps: 1000
  n_epochs: 200  
  ckpt_dir: /local_ssd/gaoziyi/deepspeed_checkpoint
  device: cuda:0
  autoregressive: True
  validate_step : 100
  restore_session:
    yes: False
    load_dir: checkpoint
    ckpt_id: 200

  dataloader:
    num_workers: 8
    batch_size: 64
    prefetch_factor: 16

  deepspeed_config: ./cfgs/deepspeed.json

logger: #default wandb
    project: weather-forecast-deepspeed
    name: swin-run-AR

seed: 114514

