model:
  model_path: model.swin_unet #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: SwinTransformerSys
  param: 
    param: 
    in_seq_length: 2
    out_seq_length: 1
    input_dim: 70
    output_dim: 70
    lat_dim: 161
    lon_dim: 161 # now must be same as lat_dim    # above are input and output parameters
    patch_size: 2
    hidden_dim: 192
    window_size: 10


data: 
  data_path : ../dataset
  npy_name: '../dataset/dataset.npy'
  preload_to_memory: True
  augment: False
  train_range: [2007,2016]
  val_range: [2016,2017]

train: 
  optimizer:
    name: Adam
    learning_rate: 0.00001
    weight_decay: 1e-5
  n_epochs: 200  
  ckpt_dir: checkpoint
  device: cuda:1
  autoregressive: True

  dataloader:
    num_workers: 8
    batch_size_train: 64
    batch_size_val: 64



logger: #default wandb
  project: weather-forecast
  name: swin-run-AR

seed: 114514

