model:
  model_path: model.VIT #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: VIT
  param: 
    in_seq_length: 2
    out_seq_length: 20
    input_dim: 70
    output_dim: 5
    lat_dim: 161
    lon_dim: 161 # now must be same as lat_dim    # above are input and output parameters
    patch_size: 4
    hidden_dim: 192
    window_size: 40

data: 
  data_path : ../dataset
  augment: False
  batch_size_train: 16
  batch_size_val: 16
train: 
  optimizer:
    name: Adam
    learning_rate: 0.0001
    weight_decay: 1e-5
  n_epochs: 100  
  ckpt_dir: checkpoint
  device: cuda:2

logger: #default wandb
  project: weather-forecast
  name: Swin_UNet_run

seed: 1

