model:
  model_path: model.VIT #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: Model
  param: 
    input_dim: 73
    output_dim: 73
    lat_dim: 32
    lon_dim: 64 # above are input and output parameters
    hidden_dim: 384
    patch_size: 2
    n_heads: 6
    num_layers: 24
    # drop_rate: 0.3
    # attn_drop_rate: 0.3
    ape: True


data: 
  data_path : /dev/shm/store/checkpoint/original_dataset
  npy_name: /dev/shm/store/original_dataset/dataset.npy
  shape: [58436, 73, 32, 64]
  preload_to_memory: False
  augment: False
  train_range: [0,56000]
  val_range: [56000,58436]

train: 
  optimizer:
    name: Adam
    learning_rate: 1
    weight_decay: 1e-5
    scheduler: 
      name: NoamLR
      hidden_dim: 192
      warmup_steps: 1000
  n_epochs: 200  
  ckpt_dir: /home/gaoziyi/weather/deepspeed_checkpoint/dropout0.3attention_0.3
  device: cuda:0
  autoregressive: True
  validate_step : 500

  batch_size: 64

  restore_session:
    yes: False
    load_dir: checkpoint
    ckpt_id: 200

  dataloader:
    num_workers: 32
    batch_size: 64
    prefetch_factor: 32

  deepspeed_config: ./cfgs/deepspeed.json

logger: #default wandb
    project: weather-forecast-deepspeed
    name: VIT-AR-hidden384-layer24

seed: 114514

hydra:
  run:
    dir: null