model:
  model_path: model.swin_unet_multivariable #'dense' or 'conv', 'dense2' or 'conv2'    
data: 
  sample: 
    name: Default
    n: 10
    T_max: 200


finetune: 
  initialize_checkpoint: /mnt/vepfs/devel/weather/deepspeed_checkpoint/VIT-nouncertain-wd0.1-climax/step_38000/mp_rank_00_model_states.pt
  
train:   
  optimizer:
    name: Adam
    learning_rate: 0.1  
    weight_decay: 1e-5
    scheduler: 
      name: NO
      T_max: 40000
      eta_min: 1.0e-9
      warmup_steps: 1000
  time_regularization: False
  n_epochs: 20
  ckpt_dir: /mnt/vepfs/devel/weather/fourcastnet_finetune_checkpoint
  validate_step: 2000
  uncertainty_loss: False
  uncertainty_finetune: False

  deepspeed_config_yaml:
    optimizer:
      type: AdamW
      params:
        lr: 5.0e-5
        betas: [0.9, 0.95]
        weight_decay: 0.1
    # gradient_clipping: 5
    


logger: #default wandb
  project: fourcastnet-finetune
  name: climax-nouncertain

seed: 114514

