model:
  model_path: model.swin_unet #'dense' or 'conv', 'dense2' or 'conv2'
  model_type: SwinTransformerSys
  param: 
    param: 
    in_seq_length: 2
    out_seq_length: 1
    input_dim: 70
    output_dim: 70
    lat_dim: 161
    lon_dim: 161 # now must be same as lat_dim    # above are input and output parameters
    patch_size: 2
    hidden_dim: 384
    window_size: 10
    ape: True

data: 
  data_path : /dev/shm/store/original_dataset/dataset.npy #the folder of 3 npy file

  preload_to_memory: False
  argument: False

validate: 
  step: 1
  device: cuda:7
  checkpoint: /mnt/vepfs/devel/weather/good_checkpoint/4/mp_rank_00_model_states.pt
  batch_size: 64


logger: #default wandb
   project: weather-finetune
   name: swin-AR-finetune

seed: 114514

